version: '3.1'

services:
  mongo:
    image: mongo
    container_name: galaxy-42_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - galaxy-42-network
  node:
    container_name: galaxy-42_node
    build:
      context: .
    ports:
      - 80:80
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn ci:dev
    networks:
      - galaxy-42-network
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
networks:
  galaxy-42-network:
volumes:
  mongodb:
